// Function to get list of suburbs
export async function getSuburbs(): Promise<string[]> {
  // This uses the same suburb data as in the services pages
  const suburbsData = {
    // Greater Sydney
    "sydney": { "state": "NSW", "region": "Greater Sydney" },
    "cbd": { "state": "NSW", "region": "Greater Sydney" },
    "haymarket": { "state": "NSW", "region": "Greater Sydney" },
    "the-rocks": { "state": "NSW", "region": "Greater Sydney" },
    "barangaroo": { "state": "NSW", "region": "Greater Sydney" },
    "pyrmont": { "state": "NSW", "region": "Greater Sydney" },
    "ultimo": { "state": "NSW", "region": "Greater Sydney" },
    "chippendale": { "state": "NSW", "region": "Greater Sydney" },
    "surry-hills": { "state": "NSW", "region": "Greater Sydney" },
    "darlinghurst": { "state": "NSW", "region": "Greater Sydney" },
    "potts-point": { "state": "NSW", "region": "Greater Sydney" },
    "elizabeth-bay": { "state": "NSW", "region": "Greater Sydney" },
    "rushcutters-bay": { "state": "NSW", "region": "Greater Sydney" },
    "woolloomooloo": { "state": "NSW", "region": "Greater Sydney" },
    "redfern": { "state": "NSW", "region": "Greater Sydney" },
    "waterloo": { "state": "NSW", "region": "Greater Sydney" },
    "zetland": { "state": "NSW", "region": "Greater Sydney" },
    "alexandria": { "state": "NSW", "region": "Greater Sydney" },
    "erskineville": { "state": "NSW", "region": "Greater Sydney" },
    
    // Eastern Suburbs
    "bondi": { "state": "NSW", "region": "Eastern Suburbs" },
    "bondi-beach": { "state": "NSW", "region": "Eastern Suburbs" },
    "bondi-junction": { "state": "NSW", "region": "Eastern Suburbs" },
    "bronte": { "state": "NSW", "region": "Eastern Suburbs" },
    "clovelly": { "state": "NSW", "region": "Eastern Suburbs" },
    "coogee": { "state": "NSW", "region": "Eastern Suburbs" },
    "maroubra": { "state": "NSW", "region": "Eastern Suburbs" },
    "kensington": { "state": "NSW", "region": "Eastern Suburbs" },
    "randwick": { "state": "NSW", "region": "Eastern Suburbs" },
    "vaucluse": { "state": "NSW", "region": "Eastern Suburbs" },
    "rose-bay": { "state": "NSW", "region": "Eastern Suburbs" },
    "double-bay": { "state": "NSW", "region": "Eastern Suburbs" },
    "bellevue-hill": { "state": "NSW", "region": "Eastern Suburbs" },
    "dover-heights": { "state": "NSW", "region": "Eastern Suburbs" },
    "queens-park": { "state": "NSW", "region": "Eastern Suburbs" },
    "pagewood": { "state": "NSW", "region": "Eastern Suburbs" },
    "eastgardens": { "state": "NSW", "region": "Eastern Suburbs" },
    "little-bay": { "state": "NSW", "region": "Eastern Suburbs" },
    "la-perouse": { "state": "NSW", "region": "Eastern Suburbs" },
    
    // Inner West
    "burwood": { "state": "NSW", "region": "Inner West" },
    "strathfield": { "state": "NSW", "region": "Inner West" },
    "newtown": { "state": "NSW", "region": "Inner West" },
    "marrickville": { "state": "NSW", "region": "Inner West" },
    "dulwich-hill": { "state": "NSW", "region": "Inner West" },
    "summer-hill": { "state": "NSW", "region": "Inner West" },
    "ashfield": { "state": "NSW", "region": "Inner West" },
    "leichhardt": { "state": "NSW", "region": "Inner West" },
    "balmain": { "state": "NSW", "region": "Inner West" },
    "rozelle": { "state": "NSW", "region": "Inner West" },
    "lilyfield": { "state": "NSW", "region": "Inner West" },
    "annandale": { "state": "NSW", "region": "Inner West" },
    "petersham": { "state": "NSW", "region": "Inner West" },
    "stanmore": { "state": "NSW", "region": "Inner West" },
    "enmore": { "state": "NSW", "region": "Inner West" },
    "croydon": { "state": "NSW", "region": "Inner West" },
    "croydon-park": { "state": "NSW", "region": "Inner West" },
    "haberfield": { "state": "NSW", "region": "Inner West" },
    "five-dock": { "state": "NSW", "region": "Inner West" },
    "drummoyne": { "state": "NSW", "region": "Inner West" },
    "glebe": { "state": "NSW", "region": "Inner West" },
    
    // North Shore
    "chatswood": { "state": "NSW", "region": "North Shore" },
    "st-leonards": { "state": "NSW", "region": "North Shore" },
    "artarmon": { "state": "NSW", "region": "Lower North Shore" },
    "willoughby": { "state": "NSW", "region": "Lower North Shore" },
    "naremburn": { "state": "NSW", "region": "Lower North Shore" },
    "northbridge": { "state": "NSW", "region": "Lower North Shore" },
    "cammeray": { "state": "NSW", "region": "Lower North Shore" },
    "cremorne": { "state": "NSW", "region": "Lower North Shore" },
    "neutral-bay": { "state": "NSW", "region": "Lower North Shore" },
    "mosman": { "state": "NSW", "region": "Lower North Shore" },
    "north-sydney": { "state": "NSW", "region": "Lower North Shore" },
    "kirribilli": { "state": "NSW", "region": "Lower North Shore" },
    "lavender-bay": { "state": "NSW", "region": "Lower North Shore" },
    "wollstonecraft": { "state": "NSW", "region": "Lower North Shore" },
    "greenwich": { "state": "NSW", "region": "Lower North Shore" },
    "lane-cove": { "state": "NSW", "region": "Lower North Shore" },
    "riverview": { "state": "NSW", "region": "Lower North Shore" },
    "longueville": { "state": "NSW", "region": "Lower North Shore" },
    
    // Upper North Shore
    "gordon": { "state": "NSW", "region": "Upper North Shore" },
    "killara": { "state": "NSW", "region": "Upper North Shore" },
    "lindfield": { "state": "NSW", "region": "Upper North Shore" },
    "roseville": { "state": "NSW", "region": "Upper North Shore" },
    "pymble": { "state": "NSW", "region": "Upper North Shore" },
    "turramurra": { "state": "NSW", "region": "Upper North Shore" },
    "wahroonga": { "state": "NSW", "region": "Upper North Shore" },
    "warrawee": { "state": "NSW", "region": "Upper North Shore" },
    "st-ives": { "state": "NSW", "region": "Upper North Shore" },
    "hornsby": { "state": "NSW", "region": "Upper North Shore" },
    "waitara": { "state": "NSW", "region": "Upper North Shore" },
    "asquith": { "state": "NSW", "region": "Upper North Shore" },
    "berowra": { "state": "NSW", "region": "Upper North Shore" },
    
    // Northern Suburbs
    "ryde": { "state": "NSW", "region": "Northern Sydney" },
    "eastwood": { "state": "NSW", "region": "Northern Sydney" },
    "epping": { "state": "NSW", "region": "Northern Sydney" },
    "macquarie-park": { "state": "NSW", "region": "Northern Sydney" },
    "north-ryde": { "state": "NSW", "region": "Northern Sydney" },
    "marsfield": { "state": "NSW", "region": "Northern Sydney" },
    "west-ryde": { "state": "NSW", "region": "Northern Sydney" },
    "meadowbank": { "state": "NSW", "region": "Northern Sydney" },
    "denistone": { "state": "NSW", "region": "Northern Sydney" },
    "putney": { "state": "NSW", "region": "Northern Sydney" },
    "gladesville": { "state": "NSW", "region": "Northern Sydney" },
    "hunters-hill": { "state": "NSW", "region": "Northern Sydney" },
    
    // Northern Beaches
    "manly": { "state": "NSW", "region": "Northern Beaches" },
    "dee-why": { "state": "NSW", "region": "Northern Beaches" },
    "brookvale": { "state": "NSW", "region": "Northern Beaches" },
    "freshwater": { "state": "NSW", "region": "Northern Beaches" },
    "curl-curl": { "state": "NSW", "region": "Northern Beaches" },
    "queenscliff": { "state": "NSW", "region": "Northern Beaches" },
    "fairlight": { "state": "NSW", "region": "Northern Beaches" },
    "balgowlah": { "state": "NSW", "region": "Northern Beaches" },
    "seaforth": { "state": "NSW", "region": "Northern Beaches" },
    "narrabeen": { "state": "NSW", "region": "Northern Beaches" },
    "collaroy": { "state": "NSW", "region": "Northern Beaches" },
    "avalon": { "state": "NSW", "region": "Northern Beaches" },
    "newport": { "state": "NSW", "region": "Northern Beaches" },
    "mona-vale": { "state": "NSW", "region": "Northern Beaches" },
    "palm-beach": { "state": "NSW", "region": "Northern Beaches" },
    
    // Hills District
    "castle-hill": { "state": "NSW", "region": "Hills District" },
    "baulkham-hills": { "state": "NSW", "region": "Hills District" },
    "bella-vista": { "state": "NSW", "region": "Hills District" },
    "kellyville": { "state": "NSW", "region": "Hills District" },
    "rouse-hill": { "state": "NSW", "region": "Hills District" },
    "pennant-hills": { "state": "NSW", "region": "Hills District" },
    "cherrybrook": { "state": "NSW", "region": "Hills District" },
    "west-pennant-hills": { "state": "NSW", "region": "Hills District" },
    "northmead": { "state": "NSW", "region": "Hills District" },
    "winston-hills": { "state": "NSW", "region": "Hills District" },
    "north-rocks": { "state": "NSW", "region": "Hills District" },
    "carlingford": { "state": "NSW", "region": "Hills District" },
    
    // Western Sydney
    "parramatta": { "state": "NSW", "region": "Western Sydney" },
    "penrith": { "state": "NSW", "region": "Western Sydney" },
    "blacktown": { "state": "NSW", "region": "Western Sydney" },
    "westmead": { "state": "NSW", "region": "Western Sydney" },
    "wentworthville": { "state": "NSW", "region": "Western Sydney" },
    "toongabbie": { "state": "NSW", "region": "Western Sydney" },
    "seven-hills": { "state": "NSW", "region": "Western Sydney" },
    "kings-langley": { "state": "NSW", "region": "Western Sydney" },
    "kings-park": { "state": "NSW", "region": "Western Sydney" },
    "prospect": { "state": "NSW", "region": "Western Sydney" },
    "girraween": { "state": "NSW", "region": "Western Sydney" },
    "pemulwuy": { "state": "NSW", "region": "Western Sydney" },
    "greystanes": { "state": "NSW", "region": "Western Sydney" },
    "merrylands": { "state": "NSW", "region": "Western Sydney" },
    "guildford": { "state": "NSW", "region": "Western Sydney" },
    "auburn": { "state": "NSW", "region": "Western Sydney" },
    "granville": { "state": "NSW", "region": "Western Sydney" },
    "harris-park": { "state": "NSW", "region": "Western Sydney" },
    "st-marys": { "state": "NSW", "region": "Western Sydney" },
    "mount-druitt": { "state": "NSW", "region": "Western Sydney" },
    "rooty-hill": { "state": "NSW", "region": "Western Sydney" },
    "doonside": { "state": "NSW", "region": "Western Sydney" },
    "quakers-hill": { "state": "NSW", "region": "Western Sydney" },
    
    // South Western Sydney
    "liverpool": { "state": "NSW", "region": "South Western Sydney" },
    "fairfield": { "state": "NSW", "region": "South Western Sydney" },
    "cabramatta": { "state": "NSW", "region": "South Western Sydney" },
    "bankstown": { "state": "NSW", "region": "South Western Sydney" },
    "revesby": { "state": "NSW", "region": "South Western Sydney" },
    "padstow": { "state": "NSW", "region": "South Western Sydney" },
    "punchbowl": { "state": "NSW", "region": "South Western Sydney" },
    "yagoona": { "state": "NSW", "region": "South Western Sydney" },
    "bass-hill": { "state": "NSW", "region": "South Western Sydney" },
    "chester-hill": { "state": "NSW", "region": "South Western Sydney" },
    "sefton": { "state": "NSW", "region": "South Western Sydney" },
    "birrong": { "state": "NSW", "region": "South Western Sydney" },
    "regents-park": { "state": "NSW", "region": "South Western Sydney" },
    "berala": { "state": "NSW", "region": "South Western Sydney" },
    "lidcombe": { "state": "NSW", "region": "South Western Sydney" },
    "condell-park": { "state": "NSW", "region": "South Western Sydney" },
    "greenacre": { "state": "NSW", "region": "South Western Sydney" },
    "chullora": { "state": "NSW", "region": "South Western Sydney" },
    "villawood": { "state": "NSW", "region": "South Western Sydney" },
    "canley-vale": { "state": "NSW", "region": "South Western Sydney" },
    "canley-heights": { "state": "NSW", "region": "South Western Sydney" },
    "warwick-farm": { "state": "NSW", "region": "South Western Sydney" },
    "casula": { "state": "NSW", "region": "South Western Sydney" },
    "prestons": { "state": "NSW", "region": "South Western Sydney" },
    "hoxton-park": { "state": "NSW", "region": "South Western Sydney" },
    "west-hoxton": { "state": "NSW", "region": "South Western Sydney" },
    "middleton-grange": { "state": "NSW", "region": "South Western Sydney" },
    
    // St George
    "hurstville": { "state": "NSW", "region": "St George" },
    "kogarah": { "state": "NSW", "region": "St George" },
    "rockdale": { "state": "NSW", "region": "St George" },
    "brighton-le-sands": { "state": "NSW", "region": "St George" },
    "sans-souci": { "state": "NSW", "region": "St George" },
    "ramsgate": { "state": "NSW", "region": "St George" },
    "monterey": { "state": "NSW", "region": "St George" },
    "dolls-point": { "state": "NSW", "region": "St George" },
    "sandringham": { "state": "NSW", "region": "St George" },
    "beverly-hills": { "state": "NSW", "region": "St George" },
    "kingsgrove": { "state": "NSW", "region": "St George" },
    "bexley": { "state": "NSW", "region": "St George" },
    "carlton": { "state": "NSW", "region": "St George" },
    "allawah": { "state": "NSW", "region": "St George" },
    "mortdale": { "state": "NSW", "region": "St George" },
    "penshurst": { "state": "NSW", "region": "St George" },
    "oatley": { "state": "NSW", "region": "St George" },
    
    // Sutherland Shire
    "cronulla": { "state": "NSW", "region": "Sutherland Shire" },
    "sutherland": { "state": "NSW", "region": "Sutherland Shire" },
    "miranda": { "state": "NSW", "region": "Sutherland Shire" },
    "caringbah": { "state": "NSW", "region": "Sutherland Shire" },
    "gymea": { "state": "NSW", "region": "Sutherland Shire" },
    "engadine": { "state": "NSW", "region": "Sutherland Shire" },
    "sylvania": { "state": "NSW", "region": "Sutherland Shire" },
    "jannali": { "state": "NSW", "region": "Sutherland Shire" },
    "como": { "state": "NSW", "region": "Sutherland Shire" },
    "oyster-bay": { "state": "NSW", "region": "Sutherland Shire" },
    "woolooware": { "state": "NSW", "region": "Sutherland Shire" },
    "loftus": { "state": "NSW", "region": "Sutherland Shire" },
    "yarrawarrah": { "state": "NSW", "region": "Sutherland Shire" },
    "grays-point": { "state": "NSW", "region": "Sutherland Shire" },
    "kirrawee": { "state": "NSW", "region": "Sutherland Shire" },
    "kareela": { "state": "NSW", "region": "Sutherland Shire" },
    "yowie-bay": { "state": "NSW", "region": "Sutherland Shire" },
    "lilli-pilli": { "state": "NSW", "region": "Sutherland Shire" },
    "port-hacking": { "state": "NSW", "region": "Sutherland Shire" },

    // Regional NSW and other states
    "newcastle": { "state": "NSW", "region": "Hunter Region" },
    "wollongong": { "state": "NSW", "region": "Illawarra" },
    "gosford": { "state": "NSW", "region": "Central Coast" },
    "bathurst": { "state": "NSW", "region": "Central West" },
    "tamworth": { "state": "NSW", "region": "New England" },
    "dubbo": { "state": "NSW", "region": "Central West" },
    "byron-bay": { "state": "NSW", "region": "Northern Rivers" },
    "melbourne": { "state": "VIC", "region": "Greater Melbourne" },
    "brunswick": { "state": "VIC", "region": "Inner North" },
    "footscray": { "state": "VIC", "region": "Inner West" },
    "brighton": { "state": "VIC", "region": "Bayside" },
    "geelong": { "state": "VIC", "region": "Barwon" },
    "ballarat": { "state": "VIC", "region": "Central Highlands" },
    "bendigo": { "state": "VIC", "region": "Loddon" },
    "frankston": { "state": "VIC", "region": "Mornington Peninsula" },
    "st-kilda": { "state": "VIC", "region": "Inner South" },
    "richmond": { "state": "VIC", "region": "Inner East" },
    "dandenong": { "state": "VIC", "region": "South East" },
    "werribee": { "state": "VIC", "region": "Western Melbourne" },
    "toorak": { "state": "VIC", "region": "Inner East" },
    "mildura": { "state": "VIC", "region": "Mallee" },
    "brisbane": { "state": "QLD", "region": "Greater Brisbane" },
    "gold-coast": { "state": "QLD", "region": "South East Queensland" },
    "sunshine-coast": { "state": "QLD", "region": "South East Queensland" },
    "cairns": { "state": "QLD", "region": "Far North Queensland" },
    "townsville": { "state": "QLD", "region": "North Queensland" },
    "toowoomba": { "state": "QLD", "region": "Darling Downs" },
    "mackay": { "state": "QLD", "region": "Central Queensland" },
    "rockhampton": { "state": "QLD", "region": "Central Queensland" },
    "bundaberg": { "state": "QLD", "region": "Wide Bay Burnett" },
    "hervey-bay": { "state": "QLD", "region": "Wide Bay Burnett" },
    "southport": { "state": "QLD", "region": "Gold Coast" },
    "west-end": { "state": "QLD", "region": "Inner Brisbane" },
    "fortitude-valley": { "state": "QLD", "region": "Inner Brisbane" },
    "perth": { "state": "WA", "region": "Greater Perth" },
    "fremantle": { "state": "WA", "region": "Greater Perth" },
    "joondalup": { "state": "WA", "region": "Northern Perth" },
    "mandurah": { "state": "WA", "region": "Peel" },
    "bunbury": { "state": "WA", "region": "South West" },
    "geraldton": { "state": "WA", "region": "Mid West" },
    "kalgoorlie": { "state": "WA", "region": "Goldfields-Esperance" },
    "broome": { "state": "WA", "region": "Kimberley" },
    "scarborough": { "state": "WA", "region": "Coastal Perth" },
    "subiaco": { "state": "WA", "region": "Inner Perth" },
    "adelaide": { "state": "SA", "region": "Greater Adelaide" },
    "glenelg": { "state": "SA", "region": "Western Adelaide" },
    "mount-gambier": { "state": "SA", "region": "Limestone Coast" },
    "whyalla": { "state": "SA", "region": "Eyre Peninsula" },
    "port-augusta": { "state": "SA", "region": "Far North" },
    "port-lincoln": { "state": "SA", "region": "Eyre Peninsula" },
    "victor-harbor": { "state": "SA", "region": "Fleurieu Peninsula" },
    "norwood": { "state": "SA", "region": "Eastern Adelaide" },
    "port-adelaide": { "state": "SA", "region": "Western Adelaide" },
    "hobart": { "state": "TAS", "region": "Greater Hobart" },
    "launceston": { "state": "TAS", "region": "Northern Tasmania" },
    "devonport": { "state": "TAS", "region": "North West" },
    "burnie": { "state": "TAS", "region": "North West" },
    "sandy-bay": { "state": "TAS", "region": "Greater Hobart" },
    "kingston": { "state": "TAS", "region": "Greater Hobart" },
    "darwin": { "state": "NT", "region": "Top End" },
    "alice-springs": { "state": "NT", "region": "Central Australia" },
    "palmerston": { "state": "NT", "region": "Top End" },
    "katherine": { "state": "NT", "region": "Katherine Region" },
    "nhulunbuy": { "state": "NT", "region": "East Arnhem" },
    "canberra": { "state": "ACT", "region": "Capital Region" },
    "belconnen": { "state": "ACT", "region": "North Canberra" },
    "woden": { "state": "ACT", "region": "South Canberra" },
    "tuggeranong": { "state": "ACT", "region": "South Canberra" },
    "gungahlin": { "state": "ACT", "region": "North Canberra" },
    "queanbeyan": { "state": "NSW", "region": "Capital Region" },
    "campbelltown": { "state": "NSW", "region": "Macarthur" }
  };

  // Format suburb names for display, converting from slug to title case
  const formattedSuburbs = Object.keys(suburbsData).map(slug => 
    slug.split('-')
      .map(word => word.charAt(0).toUpperCase() + word.slice(1))
      .join(' ')
  );

  // Sort suburbs alphabetically
  return formattedSuburbs.sort();
} 